version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: always
    ports:
      - "${BACKEND_PORT:-4000}:${BACKEND_PORT:-4000}"
    environment:
      - PORT=${BACKEND_PORT:-4000}
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    healthcheck:
      test: ["CMD", "bash", "/app/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - wealth-atlas-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    restart: always
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:${BACKEND_PORT:-4000}/graphql
    depends_on:
      - backend
    networks:
      - wealth-atlas-network

networks:
  wealth-atlas-network:
    driver: bridge
