import { addUtcDays, addUtcMonths, addUtcYears, utcDay, utcToday } from '../../utils/DateUtils';
import { Frequency } from './Frequency';

/**
 * Abstract base class for all scheduled entities (Expense, AssetTransaction, LoanPayment, etc).
 * Handles scheduling logic: next occurrence, should add, initial date, etc.
 * T = Domain object type (Expense, LoanPayment, AssetTransaction, ...)
 * F = Frequency enum type (ExpenseFrequency, InvestmentFrequency, PaymentFrequency, ...)
 */
export interface IScheduleBase {
  id: number | undefined;
  startDate: Date;
  endDate?: Date;
  frequency: Frequency;
  lastGeneratedDate?: Date;
}

/**
 * Steps a UTC-midnight date forward by one occurrence of `frequency`.
 *
 * Every month-based step is anchored to `anchorDay` (the schedule's own
 * `startDate` day-of-month), not to the previous occurrence: clamping 31 Jan
 * into February and then stepping from *that* gives 29 Feb → 29 Mar → 29 Apr,
 * silently moving a month-end schedule to the 29th for ever. See `addUtcMonths`.
 *
 * Exported so occurrence-count math (`countScheduleOccurrences`,
 * `computeScheduleEndDate`) can walk the same schedule a draft entity hasn't
 * been constructed for yet, without duplicating this switch.
 */
export function stepByFrequency(date: Date, frequency: Frequency, anchorDay: number): Date {
  switch (frequency) {
    case Frequency.DAILY:
      return addUtcDays(date, 1);
    case Frequency.WEEKLY:
      return addUtcDays(date, 7);
    case Frequency.BIWEEKLY:
      return addUtcDays(date, 14);
    case Frequency.MONTHLY:
      return addUtcMonths(date, 1, anchorDay);
    case Frequency.QUARTERLY:
      return addUtcMonths(date, 3, anchorDay);
    case Frequency.SEMI_ANNUALLY:
      return addUtcMonths(date, 6, anchorDay);
    case Frequency.ANNUALLY:
      return addUtcYears(date, 1, anchorDay);
    default:
      throw new Error('Invalid frequency');
  }
}

/**
 * Counts how many occurrences a schedule produces between `startDate` and
 * `endDate` inclusive, matching `AbstractSchedule.shouldAdd`'s semantics: the
 * first occurrence *is* `startDate`, and one landing exactly on `endDate`
 * counts. Returns 0 for an `endDate` before `startDate` (the validator
 * rejects that at submit time, but a dialog computing this live while the
 * user edits fields must not throw on a transient invalid range).
 */
export function countScheduleOccurrences(
  startDate: Date,
  endDate: Date,
  frequency: Frequency
): number {
  const start = utcDay(startDate);
  const end = utcDay(endDate);
  if (end < start) return 0;
  const anchorDay = start.getUTCDate();
  let count = 0;
  let cursor = start;
  while (cursor <= end) {
    count++;
    cursor = stepByFrequency(cursor, frequency, anchorDay);
  }
  return count;
}

/**
 * Returns the date of the Nth (last) occurrence of a schedule starting on
 * `startDate`, the inverse of `countScheduleOccurrences`. `occurrenceCount`
 * must be >= 1 -- there is no schedule with zero occurrences.
 */
export function computeScheduleEndDate(
  startDate: Date,
  frequency: Frequency,
  occurrenceCount: number
): Date {
  if (occurrenceCount < 1) {
    throw new Error('occurrenceCount must be at least 1');
  }
  const start = utcDay(startDate);
  const anchorDay = start.getUTCDate();
  let cursor = start;
  for (let i = 1; i < occurrenceCount; i++) {
    cursor = stepByFrequency(cursor, frequency, anchorDay);
  }
  return cursor;
}

export abstract class AbstractSchedule<T> implements IScheduleBase {
  public readonly id: number | undefined;
  public readonly startDate: Date;
  public readonly endDate?: Date;
  public readonly frequency: Frequency;
  public readonly lastGeneratedDate?: Date;

  constructor({ id, startDate, endDate, frequency, lastGeneratedDate }: IScheduleBase) {
    this.id = id;
    // Truncated on the way in, so a legacy row that stored a time — or one
    // generated by the old local-time arithmetic — is a clean calendar day
    // before any comparison or step is made from it.
    this.startDate = utcDay(startDate);
    this.endDate = endDate ? utcDay(endDate) : undefined;
    this.frequency = frequency;
    this.lastGeneratedDate = lastGeneratedDate ? utcDay(lastGeneratedDate) : undefined;
  }

  /**
   * Returns the next occurrence date after lastGeneratedDate (or startDate if never generated).
   */
  public getNextOccurrenceDate(): Date {
    return this.lastGeneratedDate != null
      ? this.getNextOccurrenceDateTime(this.lastGeneratedDate, this.frequency)
      : utcDay(this.startDate);
  }

  /**
   * Returns true if a new item should be generated for the given date.
   *
   * `endDate` is **inclusive**: an occurrence falling exactly on it is generated.
   * That is what the form promises the user -- the dialog summarises a schedule
   * as "until {endDate}" and labels the field "When SIP investments end" -- and it
   * is the only reading under which a schedule whose start and end are the same
   * day produces the one instalment it describes. Exclusive, such a schedule
   * validated fine (`validateSchedule` accepts end == start) and then silently
   * generated nothing, and a year of monthly SIP ending 1 Dec skipped December.
   *
   * @param nextDate The date to check
   * @param till The upper bound (defaults to today)
   */
  protected shouldAdd(nextDate: Date, till?: Date): boolean {
    return (
      nextDate <= (till ?? this.endDate ?? utcToday()) &&
      (this.endDate == null || nextDate <= this.endDate)
    );
  }

  /**
   * Returns the next occurrence date based on frequency, in UTC.
   *
   * Local-time stepping is what made the day drift. `setMonth` reads and writes
   * the *local* day-of-month, so a UTC-midnight start read as 19:00 the previous
   * day in a UTC-5 zone stepped 1 Jan → 31 Jan → 2 Mar, and under BST an
   * occurrence came out an hour before the end date it was supposed to equal.
   * Neither is visible in a zone at or ahead of UTC, which is why it survived.
   *
   * @param dateTime The base date
   * @param frequency The frequency enum
   */
  protected getNextOccurrenceDateTime(dateTime: Date, frequency: Frequency): Date {
    return stepByFrequency(utcDay(dateTime), frequency, this.startDate.getUTCDate());
  }

  public getNextOccurrenceData(): T | undefined {
    const nextOccurrenceDate = this.getNextOccurrenceDate();
    if (this.shouldAdd(nextOccurrenceDate)) {
      return this.createDataForOccurrence(nextOccurrenceDate);
    }
    return undefined;
  }

  public getPendingOccurrences(till?: Date): T[] {
    const pendingOccurrences: T[] = [];
    let nextOccurrenceDate = this.getNextOccurrenceDate();
    while (this.shouldAdd(nextOccurrenceDate, till)) {
      pendingOccurrences.push(this.createDataForOccurrence(nextOccurrenceDate));
      nextOccurrenceDate = this.getNextOccurrenceDateTime(nextOccurrenceDate, this.frequency);
    }
    return pendingOccurrences;
  }

  /**
   * Returns every occurrence the schedule describes, from `startDate` through
   * `endDate` inclusive -- the plan, not what has actually run. Unlike
   * `getPendingOccurrences`, which resumes from `lastGeneratedDate` and so
   * shrinks as occurrences are materialized into real rows, this always walks
   * the full term, so a figure derived from it (a loan's cost of borrowing)
   * stays the same regardless of how much of the schedule happens to be
   * generated yet. A schedule with no `endDate` has no fixed term to
   * enumerate, so it falls back to today, the same bound `shouldAdd` uses for
   * that case.
   */
  public getAllOccurrences(): T[] {
    const occurrences: T[] = [];
    let nextOccurrenceDate = utcDay(this.startDate);
    while (this.shouldAdd(nextOccurrenceDate)) {
      occurrences.push(this.createDataForOccurrence(nextOccurrenceDate));
      nextOccurrenceDate = this.getNextOccurrenceDateTime(nextOccurrenceDate, this.frequency);
    }
    return occurrences;
  }

  protected abstract createDataForOccurrence(date: Date): T;
}
