import { addUtcDays, addUtcMonths, addUtcYears, utcDay, utcToday } from '../../utils/DateUtils';
import { Frequency } from './Frequency';

/**
 * Abstract base class for all scheduled entities (Expense, AssetTransaction, LoanPayment, etc).
 * Handles scheduling logic: next occurrence, should add, initial date, etc.
 * T = Domain object type (Expense, LoanPayment, AssetTransaction, ...)
 * F = Frequency enum type (ExpenseFrequency, InvestmentFrequency, PaymentFrequency, ...)
 */
export interface IScheduleBase {
  id: number | undefined;
  startDate: Date;
  endDate?: Date;
  frequency: Frequency;
  lastGeneratedDate?: Date;
}

export abstract class AbstractSchedule<T> implements IScheduleBase {
  public readonly id: number | undefined;
  public readonly startDate: Date;
  public readonly endDate?: Date;
  public readonly frequency: Frequency;
  public readonly lastGeneratedDate?: Date;

  constructor({ id, startDate, endDate, frequency, lastGeneratedDate }: IScheduleBase) {
    this.id = id;
    // Truncated on the way in, so a legacy row that stored a time — or one
    // generated by the old local-time arithmetic — is a clean calendar day
    // before any comparison or step is made from it.
    this.startDate = utcDay(startDate);
    this.endDate = endDate ? utcDay(endDate) : undefined;
    this.frequency = frequency;
    this.lastGeneratedDate = lastGeneratedDate ? utcDay(lastGeneratedDate) : undefined;
  }

  /**
   * Returns the next occurrence date after lastGeneratedDate (or startDate if never generated).
   */
  public getNextOccurrenceDate(): Date {
    return this.lastGeneratedDate != null
      ? this.getNextOccurrenceDateTime(this.lastGeneratedDate, this.frequency)
      : utcDay(this.startDate);
  }

  /**
   * Returns true if a new item should be generated for the given date.
   *
   * `endDate` is **inclusive**: an occurrence falling exactly on it is generated.
   * That is what the form promises the user -- the dialog summarises a schedule
   * as "until {endDate}" and labels the field "When SIP investments end" -- and it
   * is the only reading under which a schedule whose start and end are the same
   * day produces the one instalment it describes. Exclusive, such a schedule
   * validated fine (`validateSchedule` accepts end == start) and then silently
   * generated nothing, and a year of monthly SIP ending 1 Dec skipped December.
   *
   * @param nextDate The date to check
   * @param till The upper bound (defaults to today)
   */
  protected shouldAdd(nextDate: Date, till?: Date): boolean {
    return (
      nextDate <= (till ?? this.endDate ?? utcToday()) &&
      (this.endDate == null || nextDate <= this.endDate)
    );
  }

  /**
   * Returns the next occurrence date based on frequency, in UTC.
   *
   * Local-time stepping is what made the day drift. `setMonth` reads and writes
   * the *local* day-of-month, so a UTC-midnight start read as 19:00 the previous
   * day in a UTC-5 zone stepped 1 Jan → 31 Jan → 2 Mar, and under BST an
   * occurrence came out an hour before the end date it was supposed to equal.
   * Neither is visible in a zone at or ahead of UTC, which is why it survived.
   *
   * @param dateTime The base date
   * @param frequency The frequency enum
   */
  protected getNextOccurrenceDateTime(dateTime: Date, frequency: Frequency): Date {
    const from = utcDay(dateTime);
    // Every month-based step is anchored to the day the schedule started on, not
    // to the previous occurrence: clamping 31 Jan into February and then stepping
    // from *that* gives 29 Feb → 29 Mar → 29 Apr, silently moving a month-end
    // schedule to the 29th for ever. See `addUtcMonths`.
    const anchorDay = this.startDate.getUTCDate();
    switch (frequency) {
      case Frequency.DAILY:
        return addUtcDays(from, 1);
      case Frequency.WEEKLY:
        return addUtcDays(from, 7);
      case Frequency.BIWEEKLY:
        return addUtcDays(from, 14);
      case Frequency.MONTHLY:
        return addUtcMonths(from, 1, anchorDay);
      case Frequency.QUARTERLY:
        return addUtcMonths(from, 3, anchorDay);
      case Frequency.SEMI_ANNUALLY:
        return addUtcMonths(from, 6, anchorDay);
      case Frequency.ANNUALLY:
        return addUtcYears(from, 1, anchorDay);
      default:
        throw new Error('Invalid frequency');
    }
  }

  public getNextOccurrenceData(): T | undefined {
    const nextOccurrenceDate = this.getNextOccurrenceDate();
    if (this.shouldAdd(nextOccurrenceDate)) {
      return this.createDataForOccurrence(nextOccurrenceDate);
    }
    return undefined;
  }

  public getPendingOccurrences(till?: Date): T[] {
    const pendingOccurrences: T[] = [];
    let nextOccurrenceDate = this.getNextOccurrenceDate();
    while (this.shouldAdd(nextOccurrenceDate, till)) {
      pendingOccurrences.push(this.createDataForOccurrence(nextOccurrenceDate));
      nextOccurrenceDate = this.getNextOccurrenceDateTime(nextOccurrenceDate, this.frequency);
    }
    return pendingOccurrences;
  }

  protected abstract createDataForOccurrence(date: Date): T;
}
