export enum ExpenseCategory {
  GROCERIES = 'Groceries',
  DINING_OUT = 'Dining Out',
  TRANSPORT = 'Transport',
  UTILITIES = 'Utilities',
  INTERNET = 'Internet',
  RENT = 'Rent',
  HOME_MAINTENANCE = 'Home Maintenance',
  INSURANCE = 'Insurance',
  HEALTH = 'Health',
  EDUCATION = 'Education',
  PERSONAL_CARE = 'Personal Care',
  ENTERTAINMENT = 'Entertainment',
  TRAVEL = 'Travel & Vacation',
  GIFTS = 'Gifts & Donations',
  PETS = 'Pets',
  OTHER = 'Other',
}
