name: Deploy WealthAtlas

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      region:
        description: 'AWS Region for deployment'
        required: false
        default: 'us-east-2'
        type: string

env:
  AWS_REGION: ${{ github.event.inputs.region || 'us-east-2' }}

jobs:
  deploy:
    name: 'Deploy Application'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
      
    - name: Terraform Init
      run: |
        cd terraform
        terraform init
      
    - name: Terraform Plan
      run: |
        cd terraform
        terraform plan \
          -var="mongodb_uri=${{ secrets.MONGODB_URI }}" \
          -var="jwt_secret=${{ secrets.JWT_SECRET }}" \
          -var="github_repo=${{ github.repository }}"
      
    - name: Provision Infrastructure (First Run Only)
      if: github.event_name == 'workflow_dispatch'
      run: |
        cd terraform
        terraform apply -auto-approve \
          -var="mongodb_uri=${{ secrets.MONGODB_URI }}" \
          -var="jwt_secret=${{ secrets.JWT_SECRET }}" \
          -var="github_repo=${{ github.repository }}"
      
    - name: Get Infrastructure Outputs
      id: terraform-output
      run: |
        cd terraform
        echo "APP_URL=$(terraform output -raw app_url)" >> $GITHUB_OUTPUT
        echo "SERVER_IP=$(terraform output -raw app_url | sed 's#http://##')" >> $GITHUB_OUTPUT
        
    - name: Deploy Code Changes
      if: github.ref == 'refs/heads/main'
      run: |
        chmod +x ./scripts/deploy.sh
        ./scripts/deploy.sh "${{ steps.terraform-output.outputs.SERVER_IP }}" "${{ secrets.SSH_PRIVATE_KEY }}"
        
    - name: Output Application URL
      run: |
        echo "🚀 Application deployed successfully!"
        echo "📱 You can access your application at: ${{ steps.terraform-output.outputs.APP_URL }}"
